name: 'gaming_dw_project'
version: '1.0.0'
config-version: 2

profile: 'gaming_dw_project'  # Ensure this matches your profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gaming_dw_project:
    +materialized: table  # Default materialization
    staging:
      +schema: staging
      +materialized: view  # Staging tables as views
    gaming_sessions:
      +schema: gaming_sessions
      fact_tables:
        +materialized: table
      dim_tables:
        +materialized: table
      dim_games:
        +materialized: table  # Ensure dim_games is properly included
